group:
  - files:
      - source: data/csv/housing_loan_default_rate.csv
        dest: data/TaiwanHouse/housing_loan_default_rate.csv
      - source: raw_column_definition_TaiwanHouse.md
        dest: definitions/raw_column_definition_TaiwanHouse.md
    repos: |
        wenchiehlee-money/biztrends.TW
